sudo: false

language:
  - cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgtest-dev

      compiler: gcc-7

      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libgtest-dev

      compiler: gcc-8

      env:
        - C_COMPILER=gcc-8
        - CXX_COMPILER=g++-8

install:
   - mkdir /tmp/build-gtest && cd /tmp/build-gtest
   - cmake /usr/src/gtest
   - make
   - sudo cp libgtest* /usr/lib/
   
script:
  - cmake -H. -Bbuild -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - cd build
  - cmake --build .
  - ctest

notifications:
  email: false

