sudo: false

language:
  - cpp

script:
  - cmake -H. -Bbuild -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - cd build
  - cmake --build .
  - ctest

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgtest-dev

      compiler: gcc-7

      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libgtest-dev

      compiler: gcc-8

      env:
        - C_COMPILER=gcc-8
        - CXX_COMPILER=g++-8

notifications:
  email: false

