sudo: false

language:
  - cpp

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - test/runUnitTests

notifications:
  email: false

