sudo: false

language:
  - cpp

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

      compiler: gcc-7

      env:
        - C_COMPILER=gcc-7
        - CXX_COMPILER=g++-7
        - CXX=g++-7
        - CXX_FOR_BUILD=g++7

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

      compiler: gcc-8

      env:
        - C_COMPILER=gcc-8
        - CXX_COMPILER=g++-8
        - CXX=g++-8
        - CXX_FOR_BUILD=g++8

notifications:
  email: false

